version: '3.8'

services:
  api:
    build: .
    container_name: flask_api
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    networks:
      - backend
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
